version: "3"
services:
  hub:
    image: selenium/hub
    container_name: selenium_hub

  chrome:
    image: selenium/node-chrome:4.10
    shm_size: '2g'
    depends_on:
      - hub # the service on which it depends
    environment:
    #passing below env variable so that it knows where the hub is
      - SE_EVENT_BUS_HOST=hub
    # passing below env variable so that it knows on which port it has to send the messege to hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
    # passing below env variable so that it knows on which port it can recieve the messege from hub
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    # Passing this env variable to increase the max concurrency of container i.e. to launch multiple session simultaneously.
      - SE_NODE_MAX_SESSIONS=4
    # Below env variable is used to disable password to the virtual browser visualisation. By setting it to 1 you can see whats
    # happenning on the browser container.
      - SE_VNC_NO_PASSWORD=1

  firefox:
    image: selenium/node-firefox:4.10
    shm_size: '2g'
    depends_on:
      - hub # the service on which it depends
    environment:
    #passing below env variable so that it knwos where the hub is
      - SE_EVENT_BUS_HOST=hub
    # passing below env variable so that it knows on which port it has to send the messege to hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
    # passing below env variable so that it knows on which port it can recieve the messege from hub
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    # Passing this env variable to increase the max concurrency of container i.e. to launch multiple session simultaneously.
      - SE_NODE_MAX_SESSIONS=4
    # Below env variable is used to disable password to the virtual browser visualisation. By setting it to 1 you can see whats
    # happenning on the browser container.
      - SE_VNC_NO_PASSWORD=1

  vendor-portal:
    image: swapy1994/selenium-tests
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output

  flight-reservation:
    image: swapy1994/selenium-tests
    depends_on:
      - chrome
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=4
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output