version: "3"
services:
  hub:
    image: selenium/hub
    container_name: selenium_hub
  chrome:
    image: selenium/node-chrome:4.10
    shm_size: '2g'
    depends_on:
      - hub # the service on which it depends
    deploy:
      replicas: 0
    # this option will refer the environment properties from .env file located at root folder of this docker-compose file.
    env_file: .env

  firefox:
    image: selenium/node-firefox:4.10
    shm_size: '2g'
    depends_on:
      - hub # the service on which it depends
    deploy:
      replicas: 0
    env_file: .env

  